version: 2

build:
  image: testing

conda:
  environment: doc/environment.yml

sphinx:
  configuration: doc/conf.py

formats:
  - pdf
  - epub

python:
  version: "3.8"
  install:
  - requirements: doc/requirements.txt
