# Copyright (C) 1988 1990-1992, 1994, 1997, 2007-2012 Free Software
# SPDX-FileCopyrightText: 1988 1990-1992, 1994, 1997, 2007-2012 Free Software Foundation, Inc.
# SPDX-FileContributor: Rob Savoye <rob@cygnus.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Set a default timeout to be used for the tests under UNIX, rather than
# accepting whatever default dejagnu gives us (apparently 10 seconds).
# When running the tests over NFS, under somewhat heavy load, 10 seconds
# does not seem to be enough.  Try starting with 60.
set timeout 60
verbose "Timeout is now $timeout seconds" 2

load_lib gdb.exp
