# SPDX-FileCopyrightText: 1995 1997, 2007-2012 Free Software Foundation, Inc.
# SPDX-FileContributor: Brendan Kehoe <brendan@cygnus.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# We need this file here because the targetname for the 29k board
# is `vxworks29k', not `vxworks'.  That way other tools (e.g., gcc)
# can differentiate between the stuff run on that board and others.

verbose "Loading ${srcdir}/config/vx.exp"
source ${srcdir}/config/vx.exp
