# SPDX-FileCopyrightText: 2019 David Tardon
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Test for GDB pretty printers for mdds::multi_type_matrix.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test multi_type_matrix]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_mtm" {empty mdds::multi_type_matrix}
pp_test "mtm" {mdds::multi_type_matrix \(2 columns, 4 rows\) = \{empty, 1, 2, "a", "b", 1, empty, 0.5\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
