# SPDX-FileCopyrightText: 2019 David Tardon
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Test for GDB pretty printers for mdds::rtree.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test rtree]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_tree" {empty mdds::rtree}
pp_test "tree" {mdds::rtree = \{\[\{0, 1\} - \{2, 4\}\] = "a", \[\{-3, 3\} - \{5, 8\}\] = "bc", \[\{-2, 1\} - \{3, 6\}\] = "d"\}}

pp_test "search_empty" {empty mdds::rtree::search_results}
pp_test "search_one" {mdds::rtree::search_results = \{\[\{0, 1\} - \{2, 4\}\] = "a"\}}
pp_test "search_more" {mdds::rtree::search_results = \{\[\{0, 1\} - \{2, 4\}\] = "a", \[\{-3, 3\} - \{5, 8\}\] = "bc", \[\{-2, 1\} - \{3, 6\}\] = "d"\}}

pp_test "iter_begin" {mdds::rtree::iterator = \{\[\{0, 1\} - \{2, 4\}\] = "a"\}}
# pp_test "iter_end" {non-dereferenceable mdds::rtree::iterator}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
