# Test for GDB pretty printers for mdds::rtree.
#
# This file is part of mdds.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test rtree]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_tree" {empty mdds::rtree}
pp_test "tree" {mdds::rtree = \{\[\{0, 1\} - \{2, 4\}\] = "a", \[\{-3, 3\} - \{5, 8\}\] = "bc", \[\{-2, 1\} - \{3, 6\}\] = "d"\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
