# SPDX-FileCopyrightText: 2019 David Tardon
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Test for GDB pretty printers for mdds::segment_tree.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test segment_tree]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_st" {empty mdds::segment_tree}
pp_test "st_int" {mdds::segment_tree = \{\[-10..0\] = \[0\], \[0..5\] = \[0, 1\], \[5..10\] = \[0, 1, 2\], \[10..20\] = \[0, 2\], \[40..50\] = \[3\]\}}
pp_test "st_string" {mdds::segment_tree = \{\[20..30\] = \["My hovercraft is full of eels"\]\}}

pp_test "search_none" {empty mdds::segment_tree::search_result}
pp_test "search_one" {mdds::segment_tree::search_result = \{3\}}
pp_test "search_more" {mdds::segment_tree::search_result = \{0, 1, 2\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
