# Test for GDB pretty printers for mdds::segment_tree.
#
# This file is part of mdds.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test segment_tree]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_st" {empty mdds::segment_tree}
pp_test "st_int" {mdds::segment_tree = \{\[-10..0\] = \[0\], \[0..5\] = \[0, 1\], \[5..10\] = \[0, 1, 2\], \[10..20\] = \[0, 2\], \[40..50\] = \[3\]\}}
pp_test "st_string" {mdds::segment_tree = \{\[20..30\] = \["My hovercraft is full of eels"\]\}}

pp_test "search_none" {empty mdds::segment_tree::search_result}
pp_test "search_one" {mdds::segment_tree::search_result = \{3\}}
pp_test "search_more" {mdds::segment_tree::search_result = \{0, 1, 2\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
