# SPDX-FileCopyrightText: 2019 David Tardon
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Test for GDB pretty printers for mdds::sorted_string_map.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test sorted_string_map]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_ssmap" {empty mdds::sorted_string_map}
pp_test "ssmap_int" {mdds::sorted_string_map with 4 values = \{\["aaaa"\] = 1, \["bbb"\] = 2, \["cc"\] = 3, \["d"\] = 4\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
