# Test for GDB pretty printers for mdds::sorted_string_map.
#
# This file is part of mdds.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test sorted_string_map]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_ssmap" {empty mdds::sorted_string_map}
pp_test "ssmap_int" {mdds::sorted_string_map with 4 values = \{\["aaaa"\] = 1, \["bbb"\] = 2, \["cc"\] = 3, \["d"\] = 4\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
