# Test for GDB pretty printers for mdds::trie_map.
#
# This file is part of mdds.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list mdds]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test trie_map]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_tm" {empty mdds::trie_map}
pp_test "tm_int" {mdds::trie_map = \{\["a"\] = 13, \["aa"\] = 10, \["ab"\] = 3, \["b"\] = 7\}}
pp_test "tm_str" {mdds::trie_map = \{\["a"\] = "13", \["aa"\] = "10", \["ab"\] = "3", \["b"\] = "7"\}}

pp_test "tm_search_empty" {empty mdds::trie_map::search_results}
pp_test "tm_search_one" {mdds::trie_map::search_results = \{\["b"\] = 7\}}
pp_test "tm_search_more" {mdds::trie_map::search_results = \{\["a"\] = 13, \["aa"\] = 10, \["ab"\] = 3\}}

pp_test "tm_iter_begin" {mdds::trie_map::iterator = \{first = "a", second = 13\}}
pp_test "tm_iter_end" {non-dereferenceable mdds::trie_map::iterator}
pp_test "tm_search_iter_begin" {mdds::trie_map::iterator = \{first = "b", second = 7\}}
pp_test "tm_search_iter_end" {non-dereferenceable mdds::trie_map::iterator}
pp_test "tm_search_iter_empty" {singular mdds::trie_map::iterator}

pp_test "empty_ptm" {empty mdds::packed_trie_map}
pp_test "ptm_int" {mdds::packed_trie_map = \{\["a"\] = 13, \["aa"\] = 10, \["ab"\] = 3, \["b"\] = 7\}}
pp_test "ptm_str" {mdds::packed_trie_map = \{\["a"\] = "13", \["aa"\] = "10", \["ab"\] = "3", \["b"\] = "7"\}}

pp_test "ptm_search_empty" {empty mdds::packed_trie_map::search_results}
pp_test "ptm_search_one" {mdds::packed_trie_map::search_results = \{\["b"\] = 7\}}
pp_test "ptm_search_more" {mdds::packed_trie_map::search_results = \{\["a"\] = 13, \["aa"\] = 10, \["ab"\] = 3\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
