# SPDX-FileCopyrightText: 2010 - 2012 Free Software Foundation, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This test code is part of GDB, the GNU debugger.

# Auxiliary function to set the language to fortran.
# The result is 1 (true) for success, 0 (false) for failure.

proc set_lang_fortran {} {
    if [gdb_test_no_output "set language fortran"] {
	return 0
    }
    if [gdb_test "show language" ".* source language is \"fortran\"." \
	   "set language to \"fortran\""] {
	return 0
    }
    return 1;
}
